### ISSUE TITLE
UBSAN: Issue with `stri_sub_all`

### ISSUE THREAD

**Issue by gagolews** [gagolews/stringi#348]
```
> x <- c("12 3456 789", "abc", "", NA, "667")
> stri_sub_all(x, stri_locate_all_regex(x, "[0-9]+", omit_no_match=TRUE)) <- "***"
stri_sub.cpp:566:16: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:43:28: note: nonnull attribute specified here
    #0 0x7f4816a75ae1 in stri__sub_replacement_all_single(SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, bool, SEXPREC*) /data/gannet/ripley/R/packages/tests-clang-SAN/stringi/src/stri_sub.cpp:566:9
    #1 0x7f4816a7754c in stri_sub_replacement_all(SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*) /data/gannet/ripley/R/packages/tests-clang-SAN/stringi/src/stri_sub.cpp:662:10
    #2 0x801976 in R_doDotCall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:586:17
    #3 0x9fa279 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7283:21
    #4 0x9dd71d in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #5 0xa603b7 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #6 0xa5d0a9 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #7 0x9de8f0 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #8 0xa73a8c in applydefine /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:2763:18
    #9 0x9de32a in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:695:12
    #10 0xb59be0 in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:260:2
    #11 0xb5e530 in R_ReplConsole /data/gannet/ripley/R/svn/R-devel/src/main/main.c:310:11
    #12 0xb5e315 in run_Rmainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1086:5
    #13 0x53df1a in main /data/gannet/ripley/R/svn/R-devel/src/main/Rmain.c:29:5
    #14 0x7f482502411a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #15 0x42f169 in _start (/data/gannet/ripley/R/R-clang-SAN/bin/exec/R+0x42f169)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior stri_sub.cpp:566:16 in 
> print(x)
[1] "*** *** ***" "abc"         ""            NA            "***"        
```

**Comment by gagolews** [comment]
and ASAN reports:

```
> stri_sub_all(x, stri_locate_all_regex(x, "[0-9]+", omit_no_match=TRUE)) <- "***"
stri_sub.cpp:566:15: runtime error: null pointer passed as argument 1, which is declared to never be null
    #0 0x7f3a0cabf6bd in stri__sub_replacement_all_single(SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, bool, SEXPREC*) /data/gannet/ripley/R/packages/tests-gcc-SAN/stringi/src/stri_sub.cpp:566
    #1 0x7f3a0cc98b51 in stri_sub_replacement_all(SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*) /data/gannet/ripley/R/packages/tests-gcc-SAN/stringi/src/stri_sub.cpp:674
    #2 0x623377 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7283
    #3 0x64588f in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620
    #4 0x64af95 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1780
    #5 0x64d588 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706
    #6 0x645d93 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743
    #7 0x6512ac in applydefine /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:2763
    #8 0x646419 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:695
    #9 0x6bd93e in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:260
    #10 0x6bd93e in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:200
    #11 0x6bdff0 in R_ReplConsole /data/gannet/ripley/R/svn/R-devel/src/main/main.c:310
    #12 0x6be124 in run_Rmainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1086
    #13 0x4180e8 in main /data/gannet/ripley/R/svn/R-devel/src/main/Rmain.c:29
    #14 0x7f3a1a53d11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #15 0x41a819 in _start (/data/gannet/ripley/R/gcc-SAN/bin/exec/R+0x41a819)

> print(x)
[1] "*** *** ***" "abc"         ""            NA            "***"        
```
